### ISSUE TITLE
Issues in Chapter 8 nscla_time

### ISSUE THREAD

**Issue by svishnu88** [sryza/aas#17]
Hi ,

I tried to add the nscala-time_2.10-1.8.0.jar to spark shell and imported the package. But unfortunately when i use it , i end up with this error.

scala> import com.github.nscala_time.time.Imports._
import com.github.nscala_time.time.Imports._

scala> val dt = new DateTime(2015,2,2,20,0)
scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in BuilderImplicits.class refers to term time
in value org.joda which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling BuilderImplicits.class.
That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.

Can you help me to resolve this.

**Comment by svishnu88** [comment]
I got it worked by adding the jars location in the spark-env.sh , I used both nscala and joda-time jar and it looks working to me.

But It is still not working when i try to add them using spark-shell --jars

**Comment by srowen** [comment]
@jwills @sryza 

There are a few issues here we can touch up.

- Right now the dependency is on nscala-time 1.4.0 for Scala _2.9.1_. We need to update for Scala 2.10 and can update to nscala-time 1.8.0 (which incidentally uses joda-time 2.7)
- The book shows code snippets that import and use this library starting on page ~146 but show the `--jars` command with `spark-shell` on page ~151. This info may have to occur earlier.
- The `--jars` arg shows importing `joda-time` and `geojson`. I think this has to show using the assembly JAR for `ch09-risk`, called `ch09-risk-1.0.0-jar-with-dependencies.jar` This solves the problem here by packing up all deps
- In turn that may need an extra note about calling `mvn package` to generate this assembly

**Comment by srowen** [comment]
Ah and this goes for chapters 8 and 9. Chapter 9 can perhaps call back to chapter 8's explanation of the above only rather than repeat it.

**Comment by sryza** [comment]
@srowen that all seems reasonable to me.  I'll make these changes unless you've started on them already.

**Comment by srowen** [comment]
@sryza I only updated nscala-time to make sure that worked. Go ahead, yeah, the rest should just be a few text changes.
