### ISSUE TITLE
ch06 - value containsKey is not a member of scala.collection.immutable.Map[String,Int]

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#34]
in RunLSA.scala

error: value containsKey is not a member of scala.collection.immutable.Map[String,Int]
        case (term, freq) => bTermToId.containsKey(term)

http://www.scala-lang.org/api/2.11.5/index.html#scala.collection.immutable.Map

looks like it should be "contains" instead of "containsKey"

**Comment by srowen** [comment]
Ah what happened here was that in the source code, Scala's `JavaConversions` is imported, so this gets auto-converted to a `java.util.Map` which has this method. The text doesn't show the import of `JavaConversions` though.

@sryza are you OK with the change that avoids the implicit conversion? Rather than bother adding the import. (Maybe I'll see if we can avoid most or all uses of `JavaConversions` for clarity anyway)

**Comment by sryza** [comment]
Yeah, switching to contains sounds fine to me

**Comment by srowen** [comment]
Oh, I'm blind, actually the text does have this import. Still, seems like it might be a little nicer to use contains. OK I'll hook it up.

**Comment by srowen** [comment]
Sorry, last comment: `JavaConversions` is needed by the code that uses CoreNLP. However, it occurs in listings before the one with containsKey. So we need to move the `JavaConversions` import in the text, and also switch containsKey to contain. on it ...

**Comment by srowen** [comment]
Filing an erratum now with this and a slightly different fix for the text.
