### ISSUE TITLE
ch06 - not found: value bIdfs

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#35]
In the chapter 6 text, 

case (term,freq) => (bTermIds(term), bIdfs(term) * termFreqs(term) / docTotalTerms)

bIdfs isn't defined and I cant find an equivalent in the RunLSA code.

**Comment by srowen** [comment]
Yeah, this was fixed already as an erratum in the text (not sure if you can see this link):
http://www.oreilly.com/cs/portal/edit/errata/153616?x-r=authoredit&x-redirect&au=6242

It will be fixed in the next printing / PDF release which I believe happens in a couple weeks.
Source code here should be OK.

**Comment by jackRogers** [comment]
error: org.apache.spark.broadcast.Broadcast[scala.collection.Map[String,Double]] does not take parameters
                   bIdfs(term) * termFreqs(term) / docTotalTerms)

does something else need to be imported?

**Comment by jackRogers** [comment]
Awesome, thanks dude!
