### ISSUE TITLE
ch06 - error: type mismatch in TopTermsInTopConcepts function

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#39]
```
scala> val topConceptTerms = topTermsInTopConcepts(svd, 4, 10, termIds)
<console>:108: error: type mismatch;
 found   : scala.collection.immutable.Map[String,Int]
 required: Map[Int,String]
       val topConceptTerms = topTermsInTopConcepts(svd, 4, 10, termIds)
                                                                                                           ^(under termIds)
using code

import scala.collection.mutable.ArrayBuffer
def topTermsInTopConcepts(svd: SingularValueDecomposition[RowMatrix, Matrix], numConcepts: Int,
      numTerms: Int, termIds: Map[Int, String]): Seq[Seq[(String, Double)]] = {
    val v = svd.V
    val topTerms = new ArrayBuffer[Seq[(String, Double)]]()
    val arr = v.toArray
    for (i <- 0 until numConcepts) {
        val offs = i * v.numRows
        val termWeights = arr.slice(offs, offs + v.numRows).zipWithIndex
        val sorted = termWeights.sortBy(-_._1)
        topTerms += sorted.take(numTerms).map{
            case (score, id) => (termIds(id), score)
        }
    }
    topTerms
}
```

any ideas? Also the function in the book is missing the function definition, though there is still a return statement.

**Comment by srowen** [comment]
Yeah, I think this is a subset of a slightly larger issue, where a few instances of termId and idTerm weren't consistent between the repo and text.

termIds should be a Map from Int to String and idTerms should be the opposite. I think the text may not show that correclty, but the repo does and/or it was fixed. Have a look around https://github.com/sryza/aas/blob/master/ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/ParseWikipedia.scala#L59
... this is the declaration you need for these two variables.

It is fixed in the next text update too.

Yes you won't find the book text necessarily uses the same methods or structure but should be internally consistent.
