### ISSUE TITLE
Chapter 10: adamLoad()

### ISSUE THREAD

**Issue by dbl001** [sryza/aas#45]
In the latest release of 'adam' adamLoad() has been changed to more specific methods:

E.g. - for reading 'adamLoad' has been replaced with 'loadAlignments':

```
val readsRDD:RDD[AlignmentRecord] = sc.loadAlignments("/Users/davidlaxer/genomics/reads/HG00103")
```
See:

https://github.com/bigdatagenomics/adam/issues/835#issuecomment-143513213

**Comment by srowen** [comment]
Yeah I think the code and text need to stay on one consistent version for the life of the edition. I can try updating but thought it then required some other incompatible changes

**Comment by srowen** [comment]
The packaging also changed in 0.17.0, among other things (e.g. no `adam-core` now). It works as intended with the specified version 0.16.0. I think we'd have to leave this for now.

**Comment by dbl001** [comment]
The problem with the older version of Adam is that it didn’t compile with Java 1.8.
Are you using Java 1.7 for all your work or do you change Java versions for different tools.

**Comment by srowen** [comment]
Hm, yes this repo has a build profile for testing vs Java 8:
https://github.com/sryza/aas/blob/master/.travis.yml#L17

The code itself was targeted at Java 7 + Spark 1.2, though it should work with Spark 1.5, and as far as I know Java 8. However this repo has no tests, and I suspect whatever testing @laserson did was on Java 7. It may be that ADAM doesn't work on Java 8 actually.

For now I think that's how the code will have to stay, since it needs to match up with print book. However I don't mind starting a Java 8 branch or other branches for possible future changes, not least of which to give you something to build. It's more than updating a version though. If you have a moment to figure out what needs to change we can put it in a branch or something.

**Comment by dbl001** [comment]
Ok.  The code from the book is working (with required API changes to ADAM) on:
Java 1.8.
Spark 1.5
Hadoop 3.0.0-SNAPSHOT,
Maven 3.3.3

(Spark 1.6-SNAPSHOT had build issues.

I’m trying to get the code to run in:
i. Jupyter Scala,
ii. Spark Notebook,
iii. Zeppelin,

Is the code from the book online somewhere?
(The code on github in AAS chapter 10 - ./src/main/scala/com/cloudera/datascience/genomics/RunTFPrediction.scala doesn’t correspond to anything in the book.)

**Comment by laserson** [comment]
Yes, the ADAM has changed considerably since the book was published.  The repo is in dire need of an update, for which I've created #46.  The code in the book was intended to be a skeleton for the code in the repo.
