### ISSUE TITLE
 environment require to run ch06 lsa

### ISSUE THREAD

**Issue by xiaojiongen** [sryza/aas#90]
@srowen Dear Srowen， I build the package to run lsa on my localhost, in my environment have 6 cores, and 20G memory, I need more than 48 hours to compute a 55G dataset. I think my running environment is not enough. Could you give me suggestion, if I want to run ch06 lsa, I should use how many nodes, how many memory  and how many cpus ?

**Comment by srowen** [comment]
I think these should be able to complete in a reasonable time on a single machine, because we didn't want people to have to have a large cluster. That sounds like a long time but I don't know specifically how long it's supposed to take. I know that the code was fixed a few times to run faster so make sure you use the latest.
